import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#EFF6FF', // blue-50
  },
  containerLight: {
    flex: 1,
    backgroundColor: '#F9FAFB', // gray-50
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 24,
  },
  padding: {
    padding: 24,
  },
  centered: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  headerSpace: {
    marginBottom: 32,
    alignItems: 'center',
  },
  appTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 18,
    color: '#374151',
  },
  card: {
    backgroundColor: '#FFF',
    padding: 24,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    marginBottom: 16,
  },
  errorContainer: {
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FCA5A5',
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
  },
  errorText: {
    color: '#B91C1C',
    fontSize: 14,
  },
  input: {
    width: '100%',
    padding: 16,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 12,
    fontSize: 16,
    marginBottom: 16,
    backgroundColor: '#FFF',
  },
  inputCenter: {
    width: '100%',
    padding: 16,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 12,
    fontSize: 24,
    textAlign: 'center',
    marginBottom: 16,
  },
  inputHuge: {
    fontSize: 48,
    padding: 16,
    borderWidth: 2,
    borderColor: '#D1D5DB',
    borderRadius: 12,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  buttonPrimary: {
    width: '100%',
    height: 64,
    backgroundColor: '#2563EB',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
  },
  buttonSuccess: {
    width: '100%',
    height: 64,
    backgroundColor: '#16A34A',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
  },
  buttonDisabled: {
    backgroundColor: '#D1D5DB',
  },
  buttonText: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: '600',
    marginLeft: 8,
  },
  buttonContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  linkButton: {
    marginTop: 16,
    alignItems: 'center',
  },
  linkText: {
    color: '#2563EB',
    fontSize: 16,
  },
  bodyText: {
    fontSize: 16,
    color: '#374151',
    marginBottom: 24,
    lineHeight: 24,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 18,
    color: '#374151',
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  backButtonText: {
    color: '#2563EB',
    fontSize: 16,
    marginLeft: 8,
  },
  wizardContainer: {
    maxWidth: 500,
    width: '100%',
    alignSelf: 'center',
  },
  centerText: {
    alignItems: 'center',
    marginBottom: 24,
  },
  wizardTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: 8,
    textAlign: 'center',
  },
  wizardSubtitle: {
    fontSize: 16,
    color: '#4B5563',
    textAlign: 'center',
  },
  unitText: {
    textAlign: 'center',
    fontSize: 16,
    color: '#6B7280',
    marginTop: 8,
  },
  optionsContainer: {
    gap: 16,
    marginBottom: 24,
  },
  optionButton: {
    padding: 20,
    borderWidth: 2,
    borderColor: '#D1D5DB',
    borderRadius: 12,
    backgroundColor: '#FFF',
    marginBottom: 12,
  },
  optionButtonSelected: {
    backgroundColor: '#2563EB',
    borderColor: '#1D4ED8',
  },
  optionButtonSuccess: {
    backgroundColor: '#16A34A',
    borderColor: '#15803D',
  },
  optionText: {
    fontSize: 18,
    fontWeight: '500',
    color: '#111827',
    textAlign: 'center',
  },
  optionTextSelected: {
    color: '#FFF',
  },
  sectionContainer: {
    gap: 16,
    marginBottom: 24,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '500',
    marginBottom: 16,
    color: '#111827',
  },
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  gridItem: {
    width: '48%',
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#F9FAFB',
    marginBottom: 8,
  },
  gridItemSelected: {
    backgroundColor: '#2563EB',
    borderColor: '#1D4ED8',
  },
  gridItemText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#111827',
  },
  gridItemTextSelected: {
    color: '#FFF',
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  logoutText: {
    color: '#DC2626',
    fontSize: 16,
    fontWeight: '500',
  },
  welcomeSection: {
    alignItems: 'center',
    marginBottom: 24,
  },
  welcomeTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: 8,
  },
  welcomeSubtitle: {
    fontSize: 16,
    color: '#4B5563',
  },
  highlightCard: {
    backgroundColor: '#22C55E', // Green-500 equivalent usually
    padding: 24,
    borderRadius: 16,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  highlightTitle: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: '600',
    marginLeft: 8,
  },
  highlightExerciseName: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#FFF',
    marginVertical: 12,
  },
  highlightInfo: {
    color: '#FFF',
    fontSize: 16,
  },
  highlightButton: {
    backgroundColor: '#FFF',
    marginTop: 16,
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  highlightButtonText: {
    color: '#16A34A',
    fontSize: 16,
    fontWeight: '600',
    marginRight: 8,
  },
  scheduleSection: {
    backgroundColor: '#FFF',
    padding: 20,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  sectionHeader: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: 16,
  },
  scheduleItem: {
    padding: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    marginBottom: 12,
    backgroundColor: '#F9FAFB',
  },
  scheduleItemCompleted: {
    backgroundColor: '#F0FDF4',
    borderColor: '#86EFAC',
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dateText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 4,
  },
  scheduleTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#111827',
  },
  scheduleSubtitle: {
    fontSize: 14,
    color: '#4B5563',
  },
  detailTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: 16,
  },
  tagsRow: {
    flexDirection: 'row',
    marginBottom: 24,
    gap: 12,
  },
  tagBlue: {
    backgroundColor: '#DBEAFE',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  tagTextBlue: {
    color: '#1E40AF',
    fontWeight: '500',
  },
  tagPurple: {
    backgroundColor: '#F3E8FF',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  tagTextPurple: {
    color: '#6B21A8',
    fontWeight: '500',
  },
  instructionBox: {
    marginBottom: 24,
  },
  descriptionText: {
    fontSize: 16,
    lineHeight: 24,
    color: '#374151',
  },
});